name: Import test - dev

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install packed package like a user would have
      run: |
        pip install uainepydat

    - name: import files
      run: |
        cd uainepydat
        python
        import systeminfo
        import fileio
        import duckfunc
        import datatransform
        import datahash
        import dataclean
        import dataio