name: Lint Check - dev

on:
  push:
    branches:
      - 'development'
      - develop
  pull_request:
    branches:
      - 'development'
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
