name: Unit Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run penguinz
      run: |
        mkdir -p /tmp/pynguin-results
        pynguin \
        --project-path ./uainepydat \
        --output-path /tmp/pynguin-results \
        --module-name dataclean